import { ThemeMap } from "@/types";

export const THEMES: ThemeMap = {
  "birthday-fun": {
    label: "Birthday Fun",
    emoji: "🎂",
    bg: "bg-gradient-to-br from-purple-400 via-pink-400 to-yellow-300",
    primary: "text-purple-700",
    secondary: "text-pink-600",
    accent: "bg-yellow-400",
    text: "text-purple-900",
    font: "font-['Pacifico',_cursive]",
    gradientFrom: "from-purple-500",
    gradientTo: "to-pink-500",
    cardBg: "bg-white/20 backdrop-blur-md",
    particle: "#f59e0b",
  },
  "romantic-red": {
    label: "Romantic Red",
    emoji: "❤️",
    bg: "bg-gradient-to-br from-rose-600 via-red-500 to-pink-400",
    primary: "text-rose-100",
    secondary: "text-pink-200",
    accent: "bg-rose-400",
    text: "text-white",
    font: "font-['Playfair_Display',_serif]",
    gradientFrom: "from-rose-600",
    gradientTo: "to-red-500",
    cardBg: "bg-white/10 backdrop-blur-md",
    particle: "#fb7185",
  },
  "graduation-gold": {
    label: "Graduation Gold",
    emoji: "🎓",
    bg: "bg-gradient-to-br from-yellow-700 via-yellow-500 to-amber-300",
    primary: "text-yellow-900",
    secondary: "text-amber-800",
    accent: "bg-yellow-500",
    text: "text-yellow-950",
    font: "font-['Merriweather',_serif]",
    gradientFrom: "from-yellow-600",
    gradientTo: "to-amber-400",
    cardBg: "bg-white/20 backdrop-blur-md",
    particle: "#f59e0b",
  },
  "mothers-day": {
    label: "Mother's Day",
    emoji: "🌷",
    bg: "bg-gradient-to-br from-pink-300 via-rose-200 to-fuchsia-300",
    primary: "text-rose-700",
    secondary: "text-fuchsia-700",
    accent: "bg-pink-400",
    text: "text-rose-900",
    font: "font-['Dancing_Script',_cursive]",
    gradientFrom: "from-pink-400",
    gradientTo: "to-rose-400",
    cardBg: "bg-white/30 backdrop-blur-md",
    particle: "#f472b6",
  },
  "fathers-day": {
    label: "Father's Day",
    emoji: "👔",
    bg: "bg-gradient-to-br from-blue-800 via-blue-600 to-sky-400",
    primary: "text-blue-100",
    secondary: "text-sky-200",
    accent: "bg-blue-400",
    text: "text-white",
    font: "font-['Oswald',_sans-serif]",
    gradientFrom: "from-blue-700",
    gradientTo: "to-sky-500",
    cardBg: "bg-white/10 backdrop-blur-md",
    particle: "#38bdf8",
  },
  "christmas-joy": {
    label: "Christmas Joy",
    emoji: "🎄",
    bg: "bg-gradient-to-br from-green-800 via-green-600 to-red-500",
    primary: "text-green-100",
    secondary: "text-red-200",
    accent: "bg-red-500",
    text: "text-white",
    font: "font-['Mountains_of_Christmas',_cursive]",
    gradientFrom: "from-green-700",
    gradientTo: "to-red-600",
    cardBg: "bg-white/10 backdrop-blur-md",
    particle: "#ef4444",
  },
  "new-year-glow": {
    label: "New Year Glow",
    emoji: "🎆",
    bg: "bg-gradient-to-br from-slate-900 via-purple-900 to-slate-800",
    primary: "text-yellow-300",
    secondary: "text-purple-300",
    accent: "bg-yellow-400",
    text: "text-white",
    font: "font-['Raleway',_sans-serif]",
    gradientFrom: "from-purple-800",
    gradientTo: "to-slate-900",
    cardBg: "bg-white/5 backdrop-blur-md",
    particle: "#facc15",
  },
  "general-love": {
    label: "General Love",
    emoji: "🌟",
    bg: "bg-gradient-to-br from-violet-500 via-purple-500 to-indigo-500",
    primary: "text-violet-100",
    secondary: "text-indigo-200",
    accent: "bg-violet-400",
    text: "text-white",
    font: "font-['Nunito',_sans-serif]",
    gradientFrom: "from-violet-500",
    gradientTo: "to-indigo-500",
    cardBg: "bg-white/10 backdrop-blur-md",
    particle: "#a78bfa",
  },
};

// Per-theme interactive mode defaults
// Admin can override any of these in the editor
export const THEME_INTERACTIVE_DEFAULTS: Record<string, {
  interactive_mode: boolean;
  no_button_behavior: "cycle" | "runaway" | "shrink" | "countdown";
  no_button_labels: string[];
  cta_yes_label: string;
  cta_no_label: string;
}> = {
  "romantic-red": {
    interactive_mode: true,
    no_button_behavior: "runaway",
    no_button_labels: ["Maybe Later", "Are you sure? 🥺", "Really...?", "Think harder 💭", "Last chance 💔", "Fine... 😢"],
    cta_yes_label: "Yes, Forever! ❤️",
    cta_no_label: "Maybe Later",
  },
  "birthday-fun": {
    interactive_mode: true,
    no_button_behavior: "shrink",
    no_button_labels: ["Skip Party 🎈", "Still skip?", "Missing out!", "Sure sure?", "Ok... 🎂"],
    cta_yes_label: "Let's Celebrate! 🎉",
    cta_no_label: "Skip Party 🎈",
  },
  "mothers-day": {
    interactive_mode: true,
    no_button_behavior: "cycle",
    no_button_labels: ["Not yet...", "Keep reading 🌷", "Almost there...", "One more... 💕", "Ok I'll read 😊"],
    cta_yes_label: "I Feel So Loved! 🌷",
    cta_no_label: "Not yet...",
  },
  "fathers-day": {
    interactive_mode: true,
    no_button_behavior: "cycle",
    no_button_labels: ["Hmm... 🤔", "Think harder", "Still thinking?", "You totally are! 😄", "Ok fine! 👔"],
    cta_yes_label: "Obviously! 😄",
    cta_no_label: "Hmm... 🤔",
  },
  "graduation-gold": {
    interactive_mode: true,
    no_button_behavior: "countdown",
    no_button_labels: ["Tell me more", "And more...", "Keep going...", "Almost there", "Ok I'm ready! 🎓"],
    cta_yes_label: "I Know! 🎓",
    cta_no_label: "Tell me more",
  },
  "christmas-joy": {
    interactive_mode: true,
    no_button_behavior: "countdown",
    no_button_labels: ["Check again 🎄", "Still checking...", "Almost...", "One more...", "Ho Ho Yes! 🎅"],
    cta_yes_label: "Ho Ho Yes! 🎄",
    cta_no_label: "Check again 🎄",
  },
  "new-year-glow": {
    interactive_mode: false,
    no_button_behavior: "cycle",
    no_button_labels: ["Ask me later", "Almost ready...", "One more sec", "Ok, let's go! 🎆"],
    cta_yes_label: "Born Ready! 🎆",
    cta_no_label: "Ask me later",
  },
  "general-love": {
    interactive_mode: false,
    no_button_behavior: "cycle",
    no_button_labels: ["Not yet...", "Hmm...", "Ok fine! 🌟"],
    cta_yes_label: "Open It! 🎁",
    cta_no_label: "Not yet...",
  },
};
